export interface Question {
  id: number;
  pillar: "security" | "compliance" | "culture";
  pillarName: string;
  question: string;
  options: {
    A: string;
    B: string;
    C: string;
    D: string;
  };
  scores: {
    A: number;
    B: number;
    C: number;
    D: number;
  };
}

export const QUESTIONS: Question[] = [
  // Pilar 1: Segurança da Informação (17 questões) - ISO 27701:2025 Compliance
  {
    id: 1,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "A organização implementou criptografia de dados pessoais em repouso utilizando algoritmos aprovados (AES-256 ou superior)?",
    options: {
      A: "Sim, todos os dados pessoais são criptografados com algoritmos aprovados e gestão centralizada de chaves",
      B: "Sim, a maioria dos dados pessoais é criptografada, com algumas exceções documentadas",
      C: "Apenas dados sensíveis são criptografados ou a implementação é parcial",
      D: "Não, dados pessoais não são criptografados ou não há política definida",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 2,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "São utilizados protocolos seguros (TLS 1.2+) para proteger dados pessoais em trânsito em todas as comunicações de rede?",
    options: {
      A: "Sim, todos os dados em trânsito utilizam TLS 1.2+ com certificados válidos e validação de hostname",
      B: "Sim, a maioria das comunicações utiliza TLS 1.2+, com exceções documentadas",
      C: "Apenas algumas comunicações críticas utilizam TLS, ou há versões antigas ainda em uso",
      D: "Não, não há implementação de protocolos seguros para dados em trânsito",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 3,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "A organização implementa controle de acesso baseado em funções (RBAC) com princípio de menor privilégio para dados pessoais?",
    options: {
      A: "Sim, RBAC implementado com segregação de funções, revisões periódicas e logging de acesso",
      B: "Sim, RBAC implementado, mas com revisões infrequentes ou logging limitado",
      C: "Controle de acesso existe, mas não é baseado em funções ou há exceções significativas",
      D: "Não há implementação de controle de acesso adequado ou é baseado apenas em senhas",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 4,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "Existem procedimentos formais para autenticação forte (MFA) em sistemas que processam dados pessoais?",
    options: {
      A: "Sim, MFA obrigatório para todos os usuários com acesso a dados pessoais",
      B: "Sim, MFA implementado para usuários privilegiados, mas não para todos",
      C: "MFA disponível, mas não é obrigatório ou é implementado de forma inconsistente",
      D: "Não há implementação de autenticação forte ou apenas senhas são utilizadas",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 5,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "A organização mantém logs de auditoria detalhados de todas as atividades de acesso e processamento de dados pessoais?",
    options: {
      A: "Sim, logs centralizados, imutáveis, com retenção adequada e revisão periódica",
      B: "Sim, logs mantidos, mas com retenção limitada ou revisão infrequente",
      C: "Logs existem, mas são incompletos ou não cobrem todas as atividades críticas",
      D: "Não há logging adequado ou logs não são mantidos de forma segura",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 6,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "Existem procedimentos estabelecidos para detecção, resposta e recuperação de incidentes de segurança e privacidade?",
    options: {
      A: "Sim, plano formalizado com equipe dedicada, testes regulares e comunicação pré-definida",
      B: "Sim, procedimentos documentados, mas com testes infrequentes ou comunicação limitada",
      C: "Procedimentos básicos existem, mas não são formalizados ou testados regularmente",
      D: "Não há procedimentos formais ou resposta a incidentes é ad-hoc",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 7,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "A organização realiza testes de vulnerabilidade e avaliações de penetração regularmente em sistemas que processam dados pessoais?",
    options: {
      A: "Sim, testes realizados anualmente ou mais frequentemente, com remediação documentada",
      B: "Sim, testes realizados periodicamente, mas com frequência inferior a anual",
      C: "Testes ocasionais ou apenas internos, sem documentação formal de remediação",
      D: "Não há testes de vulnerabilidade ou avaliações de penetração",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 8,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "Existe um programa de gestão de vulnerabilidades que inclua identificação, avaliação e remediação de riscos de segurança?",
    options: {
      A: "Sim, programa formalizado com SLA de remediação, priorização de risco e rastreamento",
      B: "Sim, programa existe, mas com SLA não definido ou rastreamento limitado",
      C: "Vulnerabilidades são identificadas, mas a remediação é reativa e não priorizada",
      D: "Não há programa formal de gestão de vulnerabilidades",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 9,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "A organização implementa proteção contra malware e ransomware em todos os sistemas que processam dados pessoais?",
    options: {
      A: "Sim, proteção multicamadas com antivírus, detecção comportamental e isolamento de rede",
      B: "Sim, proteção implementada, mas com cobertura limitada ou atualizações infrequentes",
      C: "Proteção básica existe, mas não cobre todos os sistemas ou é desatualizada",
      D: "Não há proteção adequada contra malware e ransomware",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 10,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "Existem procedimentos formais para backup e recuperação de dados pessoais com testes regulares de restauração?",
    options: {
      A: "Sim, backups criptografados, armazenados offline, testados regularmente com RTO/RPO definidos",
      B: "Sim, backups realizados, mas com testes infrequentes ou RTO/RPO não definidos",
      C: "Backups existem, mas não são criptografados ou testes são raros",
      D: "Não há procedimentos formais de backup ou testes de recuperação",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 11,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "A organização realiza treinamento de segurança e privacidade para todos os colaboradores que processam dados pessoais?",
    options: {
      A: "Sim, treinamento obrigatório anual com avaliação, específico por função",
      B: "Sim, treinamento realizado, mas com frequência infrequente ou sem avaliação",
      C: "Treinamento oferecido, mas não é obrigatório ou cobre poucos colaboradores",
      D: "Não há programa formal de treinamento de segurança e privacidade",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 12,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "Existe um programa de gestão de identidade e acesso (IAM) que inclua provisionamento, desprovisionamento e revisão de acesso?",
    options: {
      A: "Sim, IAM automatizado com revisão periódica, desprovisionamento imediato e auditoria",
      B: "Sim, IAM implementado, mas com processos parcialmente manuais ou revisão infrequente",
      C: "Processos de acesso existem, mas não são formalizados ou automatizados",
      D: "Não há programa formal de gestão de identidade e acesso",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 13,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "A organização implementa segmentação de rede para isolar sistemas que processam dados pessoais de redes não confiáveis?",
    options: {
      A: "Sim, segmentação implementada com firewalls, DMZ e controle de fluxo de dados",
      B: "Sim, segmentação existe, mas com regras de firewall limitadas ou revisão infrequente",
      C: "Segmentação básica existe, mas não cobre todos os sistemas críticos",
      D: "Não há segmentação de rede adequada ou todos os sistemas estão na mesma rede",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 14,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "Existem procedimentos para gestão segura de chaves criptográficas, incluindo armazenamento, rotação e destruição?",
    options: {
      A: "Sim, chaves armazenadas em HSM, rotação periódica, destruição segura documentada",
      B: "Sim, gestão de chaves implementada, mas com processos parcialmente manuais",
      C: "Chaves existem, mas gestão é informal ou não segue boas práticas",
      D: "Não há procedimentos formais para gestão de chaves criptográficas",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 15,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "A organização realiza avaliações de risco de segurança regularmente, incluindo ameaças emergentes e novos vetores de ataque?",
    options: {
      A: "Sim, avaliações formais anuais com análise de ameaças emergentes e plano de tratamento",
      B: "Sim, avaliações realizadas, mas com frequência infrequente ou análise limitada",
      C: "Avaliações ocasionais ou baseadas apenas em conformidade, sem análise de ameaças",
      D: "Não há programa formal de avaliação de risco de segurança",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 16,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "Existe um programa de inteligência de ameaças que monitore vulnerabilidades, exploits e campanhas de ataque relevantes?",
    options: {
      A: "Sim, programa formalizado com feeds de inteligência, análise e integração em resposta a incidentes",
      B: "Sim, inteligência de ameaças obtida, mas com análise limitada ou integração parcial",
      C: "Informações de ameaças são ocasionalmente consultadas, mas não sistematicamente",
      D: "Não há programa de inteligência de ameaças ou monitoramento de vulnerabilidades",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 17,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "A organização implementa proteção contra ataques de negação de serviço (DDoS) e possui plano de continuidade de negócios?",
    options: {
      A: "Sim, proteção DDoS implementada, plano de continuidade testado regularmente com RTO definido",
      B: "Sim, proteção ou plano existe, mas não ambos são robustos ou testados infrequentemente",
      C: "Proteção ou plano básico existe, mas não cobre todos os cenários críticos",
      D: "Não há proteção DDoS ou plano de continuidade de negócios adequado",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },

  // Pilar 2: Conformidade Legal (18 questões) - ISO 27701:2025 Compliance
  {
    id: 18,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização obtém consentimento explícito e informado antes de processar dados pessoais, com opções de consentimento granular?",
    options: {
      A: "Sim, consentimento explícito para cada finalidade, com opções granulares e fácil revogação",
      B: "Sim, consentimento obtido, mas com opções limitadas ou revogação não tão simples",
      C: "Consentimento obtido, mas de forma genérica ou não cobre todas as finalidades",
      D: "Não há processo formal de consentimento ou é presumido",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 19,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização implementa o direito de acesso a dados pessoais, permitindo que titulares obtenham cópia de seus dados em formato estruturado?",
    options: {
      A: "Sim, processo formalizado com resposta em até 30 dias, formato estruturado e portável",
      B: "Sim, direito implementado, mas com resposta mais lenta ou formato limitado",
      C: "Direito reconhecido, mas processo é manual ou não cobre todos os dados",
      D: "Não há implementação do direito de acesso ou é muito restritivo",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 20,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização implementa o direito de retificação, permitindo que titulares corrijam dados pessoais imprecisos?",
    options: {
      A: "Sim, processo formalizado com resposta rápida, verificação de imprecisão e notificação a terceiros",
      B: "Sim, direito implementado, mas com processo mais lento ou notificação limitada",
      C: "Direito reconhecido, mas processo é manual ou não cobre todos os dados",
      D: "Não há implementação adequada do direito de retificação",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 21,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização implementa o direito de exclusão (direito ao esquecimento) conforme regulamentações de privacidade?",
    options: {
      A: "Sim, direito implementado com processo formalizado, exclusão em todos os sistemas e notificação a terceiros",
      B: "Sim, direito implementado, mas com exceções documentadas ou notificação limitada",
      C: "Direito reconhecido, mas exclusão é manual ou não cobre todos os sistemas",
      D: "Não há implementação adequada do direito de exclusão",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 22,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização implementa o direito à portabilidade de dados, permitindo transferência de dados para outro controlador?",
    options: {
      A: "Sim, dados fornecidos em formato estruturado, legível por máquina, com transferência direta possível",
      B: "Sim, direito implementado, mas com formato limitado ou transferência direta não suportada",
      C: "Direito reconhecido, mas processo é manual ou não cobre todos os dados",
      D: "Não há implementação adequada do direito à portabilidade",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 23,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização notifica violações de dados pessoais às autoridades competentes dentro dos prazos legais (72 horas para GDPR)?",
    options: {
      A: "Sim, processo formalizado com avaliação de risco, notificação dentro do prazo e documentação",
      B: "Sim, notificação realizada, mas com processo menos formalizado ou documentação limitada",
      C: "Notificação realizada ocasionalmente, mas sem processo formal ou avaliação de risco",
      D: "Não há procedimento formal de notificação de violações",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 24,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização realiza Avaliação de Impacto de Proteção de Dados (DPIA) para processamento de alto risco?",
    options: {
      A: "Sim, DPIA realizada para todos os processamentos de alto risco, com documentação e revisão periódica",
      B: "Sim, DPIA realizada, mas para alguns processamentos ou com documentação limitada",
      C: "DPIA realizada ocasionalmente ou apenas para conformidade, sem análise profunda",
      D: "Não há processo formal de DPIA ou não é realizada",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 25,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização implementa mecanismos para transferências internacionais de dados pessoais conforme regulamentações (cláusulas contratuais padrão, adequação)?",
    options: {
      A: "Sim, mecanismos legais implementados com documentação, avaliação de adequação e revisão periódica",
      B: "Sim, mecanismos implementados, mas com documentação limitada ou revisão infrequente",
      C: "Mecanismos existem, mas não cobrem todas as transferências ou são informais",
      D: "Não há mecanismos adequados para transferências internacionais",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 26,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização mantém documentação completa de processamento de dados pessoais (registros de processamento)?",
    options: {
      A: "Sim, registros centralizados, atualizados, incluindo finalidade, categorias de dados, retenção e base legal",
      B: "Sim, registros mantidos, mas com atualização infrequente ou informações limitadas",
      C: "Registros existem, mas são incompletos ou não cobrem todos os processamentos",
      D: "Não há documentação formal de processamento de dados",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 27,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização possui acordos de processamento de dados (DPA) com todos os processadores que tratam dados pessoais?",
    options: {
      A: "Sim, DPA formalizado com cláusulas obrigatórias, revisão periódica e conformidade auditada",
      B: "Sim, DPA existe, mas com cláusulas limitadas ou revisão infrequente",
      C: "DPA existe para alguns processadores, mas não para todos ou é informal",
      D: "Não há DPA formal ou acordos com processadores",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 28,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização implementa privacidade por design, incorporando proteção de dados desde o início do desenvolvimento de sistemas?",
    options: {
      A: "Sim, privacidade integrada em requisitos, design, desenvolvimento, testes e operação",
      B: "Sim, privacidade considerada, mas em alguns estágios ou com cobertura limitada",
      C: "Privacidade considerada ocasionalmente, mas não sistematicamente no desenvolvimento",
      D: "Não há implementação de privacidade por design",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 29,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização estabelece períodos de retenção de dados pessoais e implementa exclusão automática após expiração?",
    options: {
      A: "Sim, períodos definidos por finalidade, exclusão automática implementada e revisão periódica",
      B: "Sim, períodos definidos, mas exclusão é manual ou revisão infrequente",
      C: "Períodos definidos, mas exclusão não é sistemática ou não cobre todos os dados",
      D: "Não há política formal de retenção ou exclusão de dados",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 30,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização implementa proteções especiais para dados sensíveis (dados biométricos, genéticos, de saúde, religiosos)?",
    options: {
      A: "Sim, proteções técnicas e organizacionais reforçadas, consentimento explícito e documentação",
      B: "Sim, proteções implementadas, mas com cobertura limitada ou consentimento não tão rigoroso",
      C: "Proteções básicas existem, mas não são diferenciadas para dados sensíveis",
      D: "Não há proteções especiais para dados sensíveis",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 31,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização implementa proteções para dados de crianças, incluindo verificação de idade e consentimento parental?",
    options: {
      A: "Sim, verificação de idade implementada, consentimento parental obtido, acesso limitado conforme idade",
      B: "Sim, proteções implementadas, mas com verificação limitada ou consentimento não tão rigoroso",
      C: "Proteções básicas existem, mas não são específicas para crianças",
      D: "Não há proteções especiais para dados de crianças",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 32,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização implementa transparência na coleta e processamento de dados pessoais através de políticas de privacidade claras?",
    options: {
      A: "Sim, políticas claras, acessíveis, em linguagem simples, atualizadas e disponíveis em múltiplos idiomas",
      B: "Sim, políticas existem, mas podem ser mais claras ou não estão em todos os idiomas",
      C: "Políticas existem, mas são complexas ou não cobrem todas as atividades de processamento",
      D: "Não há políticas de privacidade claras ou não são acessíveis",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 33,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização está em conformidade com regulamentações de privacidade aplicáveis (GDPR, LGPD, CCPA, PDPA)?",
    options: {
      A: "Sim, conformidade verificada regularmente através de auditorias internas e externas",
      B: "Sim, conformidade buscada, mas com lacunas identificadas ou auditorias infrequentes",
      C: "Conformidade parcial ou baseada apenas em requisitos mais óbvios",
      D: "Não há avaliação formal de conformidade com regulamentações",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 34,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização implementa proteções contra processamento automatizado e tomada de decisão exclusivamente automatizada de dados pessoais?",
    options: {
      A: "Sim, processamento automatizado documentado, direito de intervenção humana implementado e explicabilidade garantida",
      B: "Sim, proteções implementadas, mas com cobertura limitada ou explicabilidade limitada",
      C: "Proteções básicas existem, mas não cobrem todos os casos de processamento automatizado",
      D: "Não há proteções contra processamento automatizado ou tomada de decisão automatizada",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 35,
    pillar: "compliance",
    pillarName: "Conformidade Legal",
    question: "A organização implementa proteções para dados processados por sistemas de IA, incluindo transparência e viés?",
    options: {
      A: "Sim, IA auditada para viés, explicabilidade implementada, consentimento informado e monitoramento contínuo",
      B: "Sim, proteções implementadas, mas com cobertura limitada ou monitoramento infrequente",
      C: "Proteções básicas existem, mas não cobrem todos os aspectos de IA",
      D: "Não há proteções especiais para dados processados por IA",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },

  // Pilar 3: Governança e Cultura (15 questões) - ISO 27701:2025 Compliance
  {
    id: 36,
    pillar: "culture",
    pillarName: "Governança e Cultura",
    question: "A liderança executiva demonstra compromisso com privacidade através de políticas, recursos e responsabilização?",
    options: {
      A: "Sim, privacidade é prioridade estratégica com orçamento dedicado e KPIs executivos",
      B: "Sim, compromisso demonstrado, mas com recursos limitados ou KPIs não definidos",
      C: "Compromisso existente, mas privacidade não é prioridade estratégica",
      D: "Não há demonstração clara de compromisso executivo com privacidade",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 37,
    pillar: "culture",
    pillarName: "Governança e Cultura",
    question: "A organização designou um Data Protection Officer (DPO) ou responsável equivalente pela privacidade?",
    options: {
      A: "Sim, DPO designado com independência, recursos adequados e acesso direto à liderança",
      B: "Sim, DPO designado, mas com recursos limitados ou acesso indireto à liderança",
      C: "Responsável de privacidade designado, mas sem independência ou recursos adequados",
      D: "Não há DPO ou responsável designado pela privacidade",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 38,
    pillar: "culture",
    pillarName: "Governança e Cultura",
    question: "A organização mantém políticas e procedimentos de privacidade formalmente documentados e comunicados a todos os colaboradores?",
    options: {
      A: "Sim, políticas centralizadas, atualizadas, comunicadas regularmente e compreendidas por todos",
      B: "Sim, políticas documentadas e comunicadas, mas com atualização infrequente ou compreensão limitada",
      C: "Políticas existem, mas não são centralizadas ou comunicadas de forma consistente",
      D: "Não há políticas formais de privacidade ou não são comunicadas",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 39,
    pillar: "culture",
    pillarName: "Governança e Cultura",
    question: "A organização realiza treinamento obrigatório de privacidade para todos os colaboradores que processam dados pessoais?",
    options: {
      A: "Sim, treinamento obrigatório anual com avaliação, específico por função e papel",
      B: "Sim, treinamento realizado, mas com frequência infrequente ou sem avaliação",
      C: "Treinamento oferecido, mas não é obrigatório ou cobre poucos colaboradores",
      D: "Não há programa formal de treinamento de privacidade",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 40,
    pillar: "culture",
    pillarName: "Governança e Cultura",
    question: "A organização integra privacidade em processos de negócio, incluindo RH, marketing, TI e operações?",
    options: {
      A: "Sim, privacidade integrada em todos os processos com responsabilidades claras e revisão periódica",
      B: "Sim, privacidade integrada em alguns processos, mas com cobertura limitada",
      C: "Privacidade considerada em alguns processos, mas não sistematicamente",
      D: "Não há integração sistemática de privacidade em processos de negócio",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 41,
    pillar: "culture",
    pillarName: "Governança e Cultura",
    question: "A organização realiza avaliação e gestão de risco de privacidade regularmente, incluindo identificação de partes interessadas?",
    options: {
      A: "Sim, avaliação formal anual com identificação de partes interessadas, plano de tratamento e monitoramento",
      B: "Sim, avaliação realizada, mas com frequência infrequente ou identificação limitada de partes interessadas",
      C: "Avaliação ocasional ou baseada apenas em conformidade, sem plano de tratamento formal",
      D: "Não há programa formal de avaliação de risco de privacidade",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 42,
    pillar: "culture",
    pillarName: "Governança e Cultura",
    question: "A organização avalia e gerencia riscos de privacidade associados a fornecedores e terceiros?",
    options: {
      A: "Sim, avaliação formalizada com critérios de privacidade, auditoria periódica e cláusulas contratuais",
      B: "Sim, avaliação realizada, mas com critérios limitados ou auditoria infrequente",
      C: "Avaliação ocasional ou baseada apenas em conformidade, sem auditoria regular",
      D: "Não há avaliação formal de risco de privacidade de fornecedores",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 43,
    pillar: "culture",
    pillarName: "Governança e Cultura",
    question: "A organização implementa mecanismo para que colaboradores e terceiros reportem preocupações de privacidade (whistleblowing)?",
    options: {
      A: "Sim, canal formalizado, confidencial, sem retaliação, com investigação e acompanhamento",
      B: "Sim, canal existente, mas com confidencialidade limitada ou investigação infrequente",
      C: "Canal informal ou baseado em relacionamento pessoal, sem formalização",
      D: "Não há mecanismo formal para reportar preocupações de privacidade",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 44,
    pillar: "culture",
    pillarName: "Governança e Cultura",
    question: "A organização realiza revisão e melhoria contínua do programa de privacidade com base em incidentes e feedback?",
    options: {
      A: "Sim, revisão formal anual com análise de incidentes, feedback e plano de melhoria documentado",
      B: "Sim, revisão realizada, mas com frequência infrequente ou análise limitada",
      C: "Revisão ocasional ou reativa a incidentes, sem plano de melhoria formal",
      D: "Não há processo formal de revisão e melhoria contínua",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 45,
    pillar: "culture",
    pillarName: "Governança e Cultura",
    question: "A organização comunica transparentemente sobre privacidade com clientes, parceiros e reguladores?",
    options: {
      A: "Sim, comunicação proativa, clara, regular e responsiva a questões de privacidade",
      B: "Sim, comunicação realizada, mas com frequência limitada ou clareza limitada",
      C: "Comunicação reativa ou baseada apenas em requisitos legais",
      D: "Não há comunicação sistemática sobre privacidade",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 46,
    pillar: "culture",
    pillarName: "Governança e Cultura",
    question: "A organização implementa accountability, documentando decisões e ações relacionadas a privacidade?",
    options: {
      A: "Sim, documentação centralizada, rastreável, com responsabilidades claras e auditoria periódica",
      B: "Sim, documentação mantida, mas com rastreabilidade limitada ou auditoria infrequente",
      C: "Documentação existe, mas é dispersa ou não cobre todas as decisões de privacidade",
      D: "Não há documentação formal de decisões e ações de privacidade",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 47,
    pillar: "culture",
    pillarName: "Governança e Cultura",
    question: "A organização realiza auditorias internas e externas de privacidade regularmente?",
    options: {
      A: "Sim, auditorias internas anuais e externas a cada 2-3 anos, com remediação documentada",
      B: "Sim, auditorias realizadas, mas com frequência limitada ou remediação infrequente",
      C: "Auditorias ocasionais ou apenas internas, sem auditoria externa",
      D: "Não há programa formal de auditoria de privacidade",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 48,
    pillar: "culture",
    pillarName: "Governança e Cultura",
    question: "A organização mantém relacionamento proativo com autoridades de proteção de dados e reguladores?",
    options: {
      A: "Sim, comunicação regular, cooperação em investigações e participação em consultas públicas",
      B: "Sim, relacionamento mantido, mas com comunicação limitada ou participação infrequente",
      C: "Relacionamento reativo ou baseado apenas em requisitos legais",
      D: "Não há relacionamento proativo com autoridades de proteção de dados",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 49,
    pillar: "culture",
    pillarName: "Governança e Cultura",
    question: "A organização implementa proteção de dados como diferencial competitivo e valor para clientes?",
    options: {
      A: "Sim, privacidade é diferencial de marketing, certificações obtidas e reconhecimento do mercado",
      B: "Sim, privacidade comunicada como valor, mas sem certificações ou reconhecimento limitado",
      C: "Privacidade reconhecida internamente, mas não comunicada como diferencial",
      D: "Não há posicionamento de privacidade como diferencial competitivo",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 50,
    pillar: "culture",
    pillarName: "Governança e Cultura",
    question: "A organização implementa conformidade com ISO/IEC 27701:2025 e busca certificação de Privacy Information Management System (PIMS)?",
    options: {
      A: "Sim, conformidade com ISO 27701:2025 implementada, certificação obtida ou em processo",
      B: "Sim, conformidade buscada, mas com lacunas identificadas ou certificação não planejada",
      C: "Conhecimento da norma, mas implementação parcial ou não alinhada",
      D: "Não há conhecimento ou implementação de ISO 27701:2025",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
];
