export interface Question {
  id: number;
  pillar: "security" | "compliance" | "culture";
  pillarName: string;
  question: string;
  options: {
    A: string;
    B: string;
    C: string;
    D: string;
  };
  scores: {
    A: number;
    B: number;
    C: number;
    D: number;
  };
}

export const QUESTIONS: Question[] = [
  // Pilar 1: Segurança da Informação (15 questões)
  {
    id: 1,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "A empresa possui políticas e procedimentos de segurança da informação formalmente documentados e comunicados a todos os colaboradores?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 2,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "São realizados treinamentos periódicos para os colaboradores sobre as melhores práticas de segurança da informação e proteção de dados?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 3,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "Os sistemas e bancos de dados que armazenam dados pessoais são protegidos por mecanismos de controle de acesso rigorosos (autenticação forte, segregação de funções)?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 4,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "A empresa utiliza criptografia para proteger dados pessoais em trânsito e em repouso?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 5,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "Existem procedimentos estabelecidos para a gestão de incidentes de segurança da informação, incluindo detecção, resposta e recuperação?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 6,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "São realizados testes de vulnerabilidade e auditorias de segurança regularmente nos sistemas que tratam dados pessoais?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 7,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "A empresa possui um plano de continuidade de negócios e recuperação de desastres que contempla a proteção de dados pessoais?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 8,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "São utilizados firewalls e sistemas de detecção/prevenção de intrusões para proteger a rede corporativa?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 9,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "A empresa mantém registros de logs de acesso e atividades em sistemas que tratam dados pessoais para fins de auditoria e rastreabilidade?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 10,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "Os dispositivos móveis e notebooks utilizados pelos colaboradores para acesso a dados pessoais possuem políticas de segurança (criptografia, bloqueio de tela, gerenciamento remoto)?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 11,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "Há um processo formal para descarte seguro de mídias e equipamentos que contenham dados pessoais?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 12,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "A empresa realiza avaliações de risco de segurança da informação para identificar e mitigar ameaças aos dados pessoais?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 13,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "Os fornecedores e parceiros que têm acesso a dados pessoais da empresa são submetidos a avaliações de segurança e possuem cláusulas contratuais de proteção de dados?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 14,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "A empresa implementa medidas de segurança para proteger dados pessoais contra acessos não autorizados, destruição, perda, alteração, comunicação ou difusão indevida?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 15,
    pillar: "security",
    pillarName: "Segurança da Informação",
    question: "Existe um responsável pela segurança da informação (CISO ou equivalente) na estrutura organizacional da empresa?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },

  // Pilar 2: Conformidade Documental (15 questões)
  {
    id: 16,
    pillar: "compliance",
    pillarName: "Conformidade Documental",
    question: "A empresa possui um mapeamento completo dos fluxos de dados pessoais, identificando onde os dados são coletados, armazenados, processados e compartilhados?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 17,
    pillar: "compliance",
    pillarName: "Conformidade Documental",
    question: "Existem políticas de privacidade e termos de uso claros e acessíveis que informam os titulares sobre o tratamento de seus dados pessoais?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 18,
    pillar: "compliance",
    pillarName: "Conformidade Documental",
    question: "A empresa obtém o consentimento explícito dos titulares dos dados para o tratamento de dados pessoais, quando necessário e conforme a LGPD?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 19,
    pillar: "compliance",
    pillarName: "Conformidade Documental",
    question: "Os contratos com fornecedores e parceiros que tratam dados pessoais em nome da empresa contêm cláusulas específicas de proteção de dados e responsabilidades?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 20,
    pillar: "compliance",
    pillarName: "Conformidade Documental",
    question: "A empresa possui um Encarregado de Dados (DPO) formalmente nomeado e com suas responsabilidades definidas e divulgadas?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 21,
    pillar: "compliance",
    pillarName: "Conformidade Documental",
    question: "Há um registro das operações de tratamento de dados pessoais, conforme exigido pela LGPD?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 22,
    pillar: "compliance",
    pillarName: "Conformidade Documental",
    question: "A empresa possui um processo formal para atender às solicitações dos titulares de dados (acesso, correção, exclusão, portabilidade, etc.)?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 23,
    pillar: "compliance",
    pillarName: "Conformidade Documental",
    question: "As políticas e procedimentos internos da empresa estão atualizados e refletem os requisitos da LGPD?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 24,
    pillar: "compliance",
    pillarName: "Conformidade Documental",
    question: "São realizadas avaliações de impacto à proteção de dados (DPIA/RIPD) para novos projetos ou tratamentos de dados de alto risco?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 25,
    pillar: "compliance",
    pillarName: "Conformidade Documental",
    question: "A empresa possui um código de conduta ou ética que aborda a proteção de dados pessoais?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 26,
    pillar: "compliance",
    pillarName: "Conformidade Documental",
    question: "Os formulários de coleta de dados (físicos ou digitais) informam claramente a finalidade do tratamento e solicitam o consentimento quando aplicável?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 27,
    pillar: "compliance",
    pillarName: "Conformidade Documental",
    question: "A empresa possui um processo para revisão e atualização periódica de suas políticas e documentos relacionados à LGPD?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 28,
    pillar: "compliance",
    pillarName: "Conformidade Documental",
    question: "Há um processo formal para comunicação de incidentes de segurança da informação à ANPD e aos titulares, quando necessário?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 29,
    pillar: "compliance",
    pillarName: "Conformidade Documental",
    question: "A empresa adota medidas para garantir a anonimização ou pseudonimização de dados pessoais sempre que possível e adequado?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 30,
    pillar: "compliance",
    pillarName: "Conformidade Documental",
    question: "Os termos de uso e políticas de privacidade são facilmente compreensíveis e escritos em linguagem clara e acessível?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },

  // Pilar 3: Cultura de Dados (20 questões)
  {
    id: 31,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "A alta direção da empresa demonstra engajamento e apoio ativo às iniciativas de proteção de dados e conformidade com a LGPD?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 32,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "A proteção de dados é considerada um valor fundamental e parte integrante da cultura organizacional da empresa?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 33,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "Os colaboradores são incentivados a reportar preocupações ou potenciais violações de proteção de dados sem medo de retaliação?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 34,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "Existem canais claros e acessíveis para que os colaboradores possam esclarecer dúvidas sobre proteção de dados?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 35,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "A empresa promove a conscientização sobre a importância da proteção de dados em todos os níveis da organização?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 36,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "A proteção de dados é um critério considerado na fase de concepção de novos produtos, serviços ou sistemas (Privacy by Design)?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 37,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "Os líderes de equipe e gerentes são capacitados para disseminar a cultura de proteção de dados em suas respectivas áreas?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 38,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "A empresa realiza campanhas internas de comunicação para reforçar a importância da LGPD e da proteção de dados?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 39,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "A proteção de dados é incluída nos processos de integração de novos colaboradores (onboarding)?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 40,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "A empresa possui um comitê ou grupo de trabalho multidisciplinar dedicado à LGPD e proteção de dados?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 41,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "Os colaboradores compreendem suas responsabilidades individuais em relação à proteção de dados pessoais?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 42,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "A empresa incentiva a cultura de privacidade por design e por padrão (Privacy by Design and Default)?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 43,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "A empresa promove a transparência em relação ao tratamento de dados pessoais, tanto interna quanto externamente?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 44,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "Os canais de comunicação com os titulares de dados são claros e eficientes para o exercício de seus direitos?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 45,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "A empresa realiza auditorias internas para verificar a aderência às políticas e procedimentos de proteção de dados?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 46,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "Existe um processo de feedback e melhoria contínua para as iniciativas de proteção de dados?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 47,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "A empresa incentiva a colaboração entre os departamentos para garantir a proteção de dados em todas as áreas?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 48,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "A proteção de dados é um tópico regular nas reuniões de gestão e nas pautas estratégicas da empresa?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 49,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "A empresa possui um plano de comunicação para crises relacionadas à proteção de dados?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
  {
    id: 50,
    pillar: "culture",
    pillarName: "Cultura de Dados",
    question: "Os colaboradores sentem-se seguros para reportar qualquer suspeita de não conformidade com a LGPD?",
    options: {
      A: "Sim, certamente",
      B: "Sim",
      C: "Não",
      D: "Não, nunca",
    },
    scores: { A: 100, B: 65, C: 35, D: 0 },
  },
];

